name: build and deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: subhadeepthandaka/next-test:latest

      - name: Verify push
        run: docker pull subhadeepthandaka/next-test:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Connection successful!"
            sudo docker pull subhadeepthandaka/next-test:latest
            sudo docker stop next-test || true
            sudo docker rm next-test || true
            sudo docker run -d -p 3003  :3000 \
              --name next-test \
              subhadeepthandaka/next-test:latest